"use client";
import { useEffect, useMemo, useState } from "react";
type Friend={id:number;name:string;handle:string;level:string;mutual:number;color:string;status:"friend"|"suggestion"|"pending"};
type AuthUser={name:string;email:string};
type Place={id:number;name:string;type:string;score:number;distance:number;price:string;accessible:boolean;emergency:boolean;x:number;y:number;address:string;tip:string;reviews:number;categories:number[];comments:{name:string;text:string;score:number}[]};
const categories=["Qualidade do papel","Privacidade & acústica","Higiene & limpeza","Sinal / Wi-Fi","Ventilação","Itens extras"], categoryIcons=["🧻","🔒","✨","📶","❄️","🧴"];
const places:Place[]=[
{id:1,name:"Shopping Central Plaza",type:"Shopping",score:4.8,distance:220,price:"Grátis",accessible:true,emergency:true,x:46,y:42,address:"Av. da Moda, 540",tip:"A cabine 3 é maior e quase sempre está livre.",reviews:184,categories:[4.9,4.7,4.9,4.6,4.8,4.7],comments:[{name:"Marina S.",text:"Limpo, silencioso e com papel de verdade. Um achado!",score:5},{name:"Rafa T.",text:"O banheiro do piso G2 é o melhor.",score:4.7}]},
{id:2,name:"Café Grão & Prosa",type:"Cafeteria",score:4.5,distance:380,price:"Consumação",accessible:false,emergency:true,x:66,y:27,address:"Rua das Flores, 88",tip:"A chave fica ao lado do caixa.",reviews:67,categories:[4.6,4.4,4.8,4.5,4.4,4.3],comments:[{name:"Bia C.",text:"Cheiroso e muito bem cuidado.",score:4.8}]},
{id:3,name:"Posto Rota 24h",type:"Posto",score:3.7,distance:640,price:"Grátis",accessible:true,emergency:true,x:75,y:63,address:"Rodovia MG-050, km 351",tip:"Peça a chave azul na conveniência.",reviews:93,categories:[3.4,3.8,3.7,4.1,3.6,3.5],comments:[{name:"Luiz P.",text:"Resolve bem na estrada; chuveiro é pago.",score:3.8}]},
{id:4,name:"Mercado Boa Praça",type:"Mercado",score:3.1,distance:910,price:"Grátis",accessible:true,emergency:true,x:25,y:67,address:"Praça do Rosário, 16",tip:"Fica no corredor após os caixas.",reviews:41,categories:[3,3.2,3.3,2.8,3.1,3.2],comments:[{name:"Nando M.",text:"Dá para usar, mas faltou sabonete.",score:3.1}]},
{id:5,name:"Cowork Alto",type:"Coworking",score:4.7,distance:1250,price:"Pago",accessible:true,emergency:false,x:37,y:18,address:"Rua do Comércio, 201",tip:"Visitantes devem se identificar na recepção.",reviews:52,categories:[4.8,4.9,4.7,5,4.6,4.2],comments:[{name:"Lia F.",text:"Privacidade nível premium e Wi-Fi voando.",score:4.9}]}
];
const labelFor=(n:number)=>n>=4.5?["👑","Trono Real"]:n>=3.5?["👍","Seguro & Confortável"]:n>=2.5?["⚠️","Só em Emergência"]:["☣️","Evite a Todo Custo"];
const initialFriends:Friend[]=[{id:1,name:"Marina Silva",handle:"@marinatrons",level:"Rainha do Papel",mutual:8,color:"#bb765c",status:"friend"},{id:2,name:"Rafael Tavares",handle:"@rafan2",level:"Caçador de Tronos",mutual:4,color:"#577a74",status:"friend"},{id:3,name:"Beatriz Costa",handle:"@biahigiene",level:"Fiscal da Limpeza",mutual:11,color:"#8b6996",status:"friend"},{id:4,name:"Pedro Henrique",handle:"@phrotas",level:"Desbravador",mutual:6,color:"#a57a3e",status:"suggestion"},{id:5,name:"Erika Alves",handle:"@erikaviaja",level:"Salvadora da Pátria",mutual:3,color:"#547493",status:"suggestion"}];
export default function Home(){
const [selected,setSelected]=useState(places[0]),[detail,setDetail]=useState(false),[review,setReview]=useState(false),[profile,setProfile]=useState(false),[friendsOpen,setFriendsOpen]=useState(false),[dark,setDark]=useState(false),[filter,setFilter]=useState("Todos"),[ratings,setRatings]=useState([5,5,5,5,5,5]),[comment,setComment]=useState(""),[toast,setToast]=useState(""),[checkins,setCheckins]=useState(12),[photo,setPhoto]=useState(""),[friends,setFriends]=useState<Friend[]>(initialFriends),[friendSearch,setFriendSearch]=useState(""),[user,setUser]=useState<AuthUser|null>(null),[authMode,setAuthMode]=useState<"login"|"signup">("login"),[authReady,setAuthReady]=useState(false),[authName,setAuthName]=useState(""),[authEmail,setAuthEmail]=useState(""),[authPassword,setAuthPassword]=useState(""),[coords,setCoords]=useState({lat:-20.7184,lon:-46.6093}),[locationLabel,setLocationLabel]=useState("Passos, MG"),[geoBusy,setGeoBusy]=useState(false),[placeSearch,setPlaceSearch]=useState(""),[searchResults,setSearchResults]=useState<{display_name:string;lat:string;lon:string}[]>([]),[searchBusy,setSearchBusy]=useState(false);
useEffect(()=>{if(localStorage.getItem("poopsquare-theme")==="dark"){setDark(true);document.documentElement.classList.add("dark")};const session=localStorage.getItem("poopsquare-session");if(session)try{setUser(JSON.parse(session))}catch{};setAuthReady(true);const savedPhoto=localStorage.getItem("poopsquare-profile-photo");if(savedPhoto)setPhoto(savedPhoto);const savedFriends=localStorage.getItem("poopsquare-friends");if(savedFriends)try{setFriends(JSON.parse(savedFriends))}catch{}},[]);
const toggleTheme=()=>setDark(v=>{document.documentElement.classList.toggle("dark",!v);localStorage.setItem("poopsquare-theme",!v?"dark":"light");return !v});
const filtered=useMemo(()=>places.filter(p=>filter==="Todos"||filter==="Tronos Reais"&&p.score>=4.5||filter==="Grátis"&&p.price==="Grátis"||filter==="PCD"&&p.accessible||filter==="Emergência"&&p.emergency),[filter]);
const liveScore=ratings.reduce((a,b)=>a+b,0)/6,checkIn=()=>{setCheckins(v=>v+1);setToast("📍 Check-in feito! +10 XP");setTimeout(()=>setToast(""),2600)},submit=()=>{setReview(false);setToast("🎉 Avaliação publicada! Badge Desbravador desbloqueado");setComment("");setTimeout(()=>setToast(""),3500)};
const saveFriends=(next:Friend[])=>{setFriends(next);localStorage.setItem("poopsquare-friends",JSON.stringify(next))};
const updateFriend=(id:number)=>{const next=friends.map(f=>f.id===id?{...f,status:f.status==="suggestion"?"pending":"friend"} as Friend:f);saveFriends(next);setToast(friends.find(f=>f.id===id)?.status==="suggestion"?"👋 Convite enviado!":"🤝 Solicitação aceita!");setTimeout(()=>setToast(""),2600)};
const uploadPhoto=(file?:File)=>{if(!file)return;if(file.size>2500000){setToast("A foto deve ter no máximo 2,5 MB");setTimeout(()=>setToast(""),2500);return}const reader=new FileReader();reader.onload=()=>{const value=String(reader.result);setPhoto(value);try{localStorage.setItem("poopsquare-profile-photo",value)}catch{}setToast("📸 Foto de perfil atualizada!");setTimeout(()=>setToast(""),2500)};reader.readAsDataURL(file)};
const visibleFriends=friends.filter(f=>(f.name+f.handle).toLowerCase().includes(friendSearch.toLowerCase()));
const authenticate=(e:React.FormEvent)=>{e.preventDefault();const session={name:authMode==="signup"?(authName.trim()||"Novo explorador"):"Luiz Fernando Piantino",email:authEmail.trim()};localStorage.setItem("poopsquare-session",JSON.stringify(session));setUser(session);setToast(authMode==="signup"?"🎉 Perfil criado! Bem-vindo ao PoopSquare":"👋 Login realizado com sucesso");setTimeout(()=>setToast(""),2800)};
const logout=()=>{localStorage.removeItem("poopsquare-session");setUser(null);setProfile(false);setAuthPassword("");setToast("")};
const locateMe=()=>{if(!navigator.geolocation){setToast("GPS não disponível neste aparelho");return}setGeoBusy(true);navigator.geolocation.getCurrentPosition(async pos=>{const next={lat:pos.coords.latitude,lon:pos.coords.longitude};setCoords(next);setLocationLabel("Sua localização atual");setGeoBusy(false);try{const res=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${next.lat}&lon=${next.lon}`);const data=await res.json();if(data.display_name)setLocationLabel(data.display_name.split(",").slice(0,3).join(","))}catch{}},()=>{setGeoBusy(false);setToast("Permita o acesso à localização para usar o GPS");setTimeout(()=>setToast(""),3000)},{enableHighAccuracy:true,timeout:12000})};
const searchPlaces=async(e:React.FormEvent)=>{e.preventDefault();if(!placeSearch.trim())return;setSearchBusy(true);try{const res=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&countrycodes=br&q=${encodeURIComponent(placeSearch)}`);setSearchResults(await res.json())}catch{setToast("Não foi possível buscar agora");setTimeout(()=>setToast(""),2500)}finally{setSearchBusy(false)}};
const chooseLocation=(r:{display_name:string;lat:string;lon:string})=>{setCoords({lat:Number(r.lat),lon:Number(r.lon)});setLocationLabel(r.display_name.split(",").slice(0,3).join(","));setSearchResults([]);setPlaceSearch("")};
const mapSrc=`https://www.openstreetmap.org/export/embed.html?bbox=${coords.lon-.025}%2C${coords.lat-.018}%2C${coords.lon+.025}%2C${coords.lat+.018}&layer=mapnik&marker=${coords.lat}%2C${coords.lon}`;
if(!authReady)return <main className="auth-loading"><span className="brand-mark">P</span></main>;
if(!user)return <main className="auth-screen"><section className="auth-art"><div className="auth-brand"><span className="brand-mark">P</span><span>PoopSquare<small>Seu alívio começa aqui.</small></span></div><div><span className="eyebrow">A COMUNIDADE DO ALÍVIO</span><h1>Todo mundo merece<br/>um <em>bom trono.</em></h1><p>Encontre banheiros próximos, compartilhe avaliações e salve seus amigos de um perrengue.</p><div className="auth-proof"><span>👑</span><div><b>+2.840 tronos avaliados</b><small>por exploradores como você</small></div></div></div></section><section className="auth-box"><div className="auth-mobile-logo"><span className="brand-mark">P</span><b>PoopSquare</b></div><span className="eyebrow">{authMode==="login"?"BEM-VINDO DE VOLTA":"ENTRE PARA A COMUNIDADE"}</span><h2>{authMode==="login"?"Acesse sua conta":"Crie seu perfil"}</h2><p>{authMode==="login"?"Seus tronos e amigos estão esperando.":"É rápido, gratuito e sem aperto."}</p><form onSubmit={authenticate}>{authMode==="signup"&&<label>Nome completo<input value={authName} onChange={e=>setAuthName(e.target.value)} placeholder="Como devemos chamar você?" required/></label>}<label>E-mail<input type="email" value={authEmail} onChange={e=>setAuthEmail(e.target.value)} placeholder="voce@email.com" required/></label><label>Senha<input type="password" value={authPassword} onChange={e=>setAuthPassword(e.target.value)} placeholder="Mínimo de 6 caracteres" minLength={6} required/></label><div className="auth-options"><label><input type="checkbox"/> Lembrar de mim</label>{authMode==="login"&&<button type="button">Esqueci a senha</button>}</div><button className="auth-submit">{authMode==="login"?"Entrar no PoopSquare":"Criar meu perfil"} →</button></form><div className="auth-switch">{authMode==="login"?"Ainda não tem conta? ":"Já possui uma conta? "}<button onClick={()=>setAuthMode(authMode==="login"?"signup":"login")}>{authMode==="login"?"Criar perfil":"Fazer login"}</button></div><small className="auth-note">Ao continuar, você concorda com os Termos de Uso e Política de Privacidade.</small></section></main>;
return <main className="app-shell">
<header className="topbar"><button className="brand" onClick={()=>{setDetail(false);setReview(false);setProfile(false)}}><span className="brand-mark">P</span><span>PoopSquare<small>Seu alívio começa aqui.</small></span></button><div className="header-actions"><button className="icon-btn" onClick={toggleTheme} aria-label="Alternar tema">{dark?"☀️":"🌙"}</button><button className="header-logout" onClick={logout}>Sair</button><button className={`avatar ${photo?"has-photo":""}`} onClick={()=>setProfile(true)} aria-label="Abrir perfil">{photo?<img src={photo} alt={`Foto de ${user.name}`}/>:user.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</button></div></header>
<section className="hero"><div><span className="eyebrow">AO REDOR DE VOCÊ</span><h1>Encontre o trono certo,<br/><em>na hora certa.</em></h1><p>Banheiros avaliados pela comunidade. Sem surpresas, sem perrengue.</p></div><div className="level-card"><div className="level-icon">🏆</div><div><small>NÍVEL 4</small><strong>Caçador de Tronos</strong><div className="xp"><i style={{width:"68%"}}/></div><span>{checkins} check-ins · 680 XP</span></div></div></section>
<div className="filters" role="group" aria-label="Filtros">{["Todos","Emergência","Tronos Reais","Grátis","PCD"].map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f==="Todos"?"◉ ":f==="Emergência"?"⚡ ":f==="Tronos Reais"?"👑 ":f==="Grátis"?"◌ ":"♿ "}{f}</button>)}</div>
<section className="explore-grid"><div className="map-column"><form className="map-search" onSubmit={searchPlaces}><span>⌕</span><input value={placeSearch} onChange={e=>setPlaceSearch(e.target.value)} placeholder="Buscar endereço, praça ou estabelecimento"/><button>{searchBusy?"Buscando...":"Buscar"}</button>{searchResults.length>0&&<div className="map-results">{searchResults.map((r,i)=><button type="button" key={i} onClick={()=>chooseLocation(r)}>📍 <span>{r.display_name}</span></button>)}</div>}</form><div className="map-card real-map"><iframe title="Mapa OpenStreetMap" src={mapSrc} loading="lazy"/><div className="map-status"><span/> {locationLabel}</div><button className="locate" onClick={locateMe} aria-label="Usar minha localização">{geoBusy?"…":"⌖"}</button><a className="osm-credit" href={`https://www.openstreetmap.org/?mlat=${coords.lat}&mlon=${coords.lon}#map=15/${coords.lat}/${coords.lon}`} target="_blank" rel="noreferrer">Ver mapa maior ↗</a></div><button className="gps-action" onClick={locateMe}>◎ {geoBusy?"Localizando...":"Usar minha localização atual"}</button></div>
<div className="nearby"><div className="section-title"><div><span>{filtered.length} LOCAIS PRÓXIMOS</span><h2>Melhores por perto</h2></div><button>Distância ↕</button></div><div className="place-list">{filtered.map((p,i)=><article key={p.id} className={`place-card ${selected.id===p.id?"chosen":""}`} onClick={()=>setSelected(p)}><div className={`place-photo photo-${i%5}`}><span>{p.type==="Shopping"?"🏬":p.type==="Cafeteria"?"☕":p.type==="Posto"?"⛽":p.type==="Mercado"?"🛒":"💻"}</span><b>#{i+1}</b></div><div className="place-copy"><div className="place-top"><span>{p.type}</span><span>• {p.distance<1000?p.distance+" m":(p.distance/1000).toFixed(1)+" km"}</span></div><h3>{p.name}</h3><div className="score-row"><strong>{p.score.toFixed(1)}</strong><span className="stars">★★★★★</span><small>({p.reviews})</small></div><div className="tags"><span>{p.price==="Grátis"?"✓ Grátis":p.price}</span>{p.accessible&&<span>♿ PCD</span>}</div></div><button className="arrow" onClick={e=>{e.stopPropagation();setSelected(p);setDetail(true)}}>›</button></article>)}</div></div></section>
<nav className="bottom-nav"><button className={!profile?"active":""} onClick={()=>setProfile(false)}>⌖<span>Explorar</span></button><button>♡<span>Salvos</span></button><button className="checkin" onClick={checkIn}>＋<span>Check-in</span></button><button>♛<span>Ranking</span></button><button className={profile?"active":""} onClick={()=>setProfile(true)}>☻<span>Perfil</span></button></nav>
{detail&&<div className="overlay" onClick={()=>setDetail(false)}><section className="detail-panel" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDetail(false)}>×</button><div className="detail-head"><span>{selected.type}</span><h2>{selected.name}</h2><p>📍 {selected.address} · {selected.distance} m</p></div><div className="score-hero"><div><strong>{selected.score.toFixed(1)}</strong><small>/ 5.0</small></div><span>{labelFor(selected.score)[0]} {labelFor(selected.score)[1]}</span></div><div className="bars">{categories.map((c,i)=><div key={c}><span>{categoryIcons[i]} {c}</span><i><b style={{width:`${selected.categories[i]*20}%`}}/></i><strong>{selected.categories[i].toFixed(1)}</strong></div>)}</div><div className="quick-tip"><b>💡 Dica de ouro</b><p>{selected.tip}</p></div><div className="comments"><h3>O que a galera diz <small>{selected.reviews} avaliações</small></h3>{selected.comments.map((c,i)=><article key={i}><div className="comment-avatar">{c.name[0]}</div><div><b>{c.name}</b><span> ★ {c.score}</span><p>{c.text}</p></div></article>)}</div><div className="detail-actions"><button onClick={checkIn}>📍 Fazer check-in</button><button className="primary" onClick={()=>setReview(true)}>✦ Avaliar este trono</button></div></section></div>}
{review&&<div className="overlay review-overlay"><section className="review-modal"><button className="close" onClick={()=>setReview(false)}>×</button><span className="eyebrow">CHECK-IN N2</span><h2>Como foi o trono?</h2><p>{selected.name}</p><div className="live-score"><strong>{liveScore.toFixed(1)}</strong><span>/ 5.0</span><b>{labelFor(liveScore)[0]} {labelFor(liveScore)[1]}</b></div><div className="rating-list">{categories.map((c,i)=><div key={c}><label>{categoryIcons[i]} <span>{c}</span></label><div>{[1,2,3,4,5].map(star=><button key={star} className={ratings[i]>=star?"lit":""} onClick={()=>setRatings(r=>r.map((v,j)=>j===i?star:v))}>★</button>)}</div></div>)}</div><label className="comment-field">Comentário rápido<textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Conte o segredo deste trono..." maxLength={180}/><small>{comment.length}/180</small></label><div className="toggle-tags"><button className="on">✓ Gratuito</button><button>🔑 Tem chave</button><button>⚥ Unissex</button></div><button className="submit" onClick={submit}>Publicar avaliação · +50 XP</button></section></div>}
{profile&&<div className="profile-view"><div className="profile-wrap"><div className="profile-toolbar"><button className="profile-close" onClick={()=>setProfile(false)}>← Voltar para explorar</button><button className="profile-logout" onClick={logout}>↪ Sair da conta</button></div><section className="profile-hero"><div className="cover-pattern"/><label className="profile-photo" title="Alterar foto">{photo?<img src={photo} alt={`Foto de ${user.name}`}/>:<span>{user.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</span>}<i>📷</i><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>uploadPhoto(e.target.files?.[0])}/></label><div className="profile-title"><div><span className="eyebrow">CAÇADOR DE TRONOS · NÍVEL 4</span><h1>{user.name}</h1><p>📍 Passos, MG · {user.email}</p></div><button className="edit-profile">✎ Editar perfil</button></div></section>
<section className="profile-stats"><div><strong>{checkins}</strong><span>Check-ins</span></div><div><strong>9</strong><span>Avaliações</span></div><button onClick={()=>setFriendsOpen(true)}><strong>{friends.filter(f=>f.status==="friend").length}</strong><span>Amigos</span></button><div><strong>4.6</strong><span>Nota média</span></div></section>
<div className="profile-grid"><div className="profile-main"><section className="profile-card"><div className="card-heading"><div><span className="eyebrow">COLEÇÃO</span><h2>Conquistas</h2></div><button>Ver todas</button></div><div className="badges"><article><i>👑</i><b>Mestre do Trono</b><span>5 tronos reais</span></article><article><i>🧻</i><b>Crítico de Papel</b><span>10 avaliações</span></article><article><i>🛟</i><b>Salvador da Pátria</b><span>3 dicas úteis</span></article><article className="locked"><i>🔒</i><b>Prefeito</b><span>Faltam 2 check-ins</span></article></div></section><section className="profile-card"><div className="card-heading"><div><span className="eyebrow">ATIVIDADE</span><h2>Últimos check-ins</h2></div></div><div className="timeline"><article><i>👑</i><div><b>Shopping Central Plaza</b><p>Você avaliou com <strong>4.8 ★</strong></p><span>Hoje · 10:42</span></div></article><article><i>⛽</i><div><b>Posto Rota 24h</b><p>Check-in realizado · +10 XP</p><span>Ontem · 18:21</span></div></article><article><i>☕</i><div><b>Café Grão & Prosa</b><p>Nova dica publicada</p><span>18 de ago. · 14:05</span></div></article></div></section></div>
<aside className="friends-card"><div className="card-heading"><div><span className="eyebrow">SUA TURMA</span><h2>Amigos</h2></div><button onClick={()=>setFriendsOpen(true)}>Ver todos</button></div>{friends.filter(f=>f.status==="friend").slice(0,3).map(f=><article key={f.id}><div className="friend-avatar" style={{background:f.color}}>{f.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</div><div><b>{f.name}</b><span>{f.level}</span></div><button>•••</button></article>)}<button className="add-friends" onClick={()=>setFriendsOpen(true)}>＋ Encontrar amigos</button><div className="mayor-card"><span>🏛️</span><div><small>PREFEITO ATUAL</small><b>Shopping Central Plaza</b><p>Mais 2 check-ins e o trono é seu.</p></div></div></aside></div></div></div>}
{friendsOpen&&<div className="overlay review-overlay"><section className="friends-modal"><button className="close" onClick={()=>setFriendsOpen(false)}>×</button><span className="eyebrow">COMUNIDADE</span><h2>Amigos do trono</h2><p>Encontre pessoas e compartilhe boas descobertas.</p><label className="friend-search">⌕<input value={friendSearch} onChange={e=>setFriendSearch(e.target.value)} placeholder="Buscar por nome ou @usuário"/></label><div className="friend-tabs"><button className="active">Todos</button><button>Meus amigos</button><button>Solicitações <b>2</b></button></div><div className="friends-list">{visibleFriends.map(f=><article key={f.id}><div className="friend-avatar large" style={{background:f.color}}>{f.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</div><div><b>{f.name}</b><span>{f.handle} · {f.mutual} amigos em comum</span><small>{f.level}</small></div>{f.status==="friend"?<button className="friend-done">✓ Amigos</button>:f.status==="pending"?<button className="friend-pending">Enviado</button>:<button className="friend-add" onClick={()=>updateFriend(f.id)}>＋ Adicionar</button>}</article>)}</div></section></div>}
{toast&&<div className="toast">{toast}</div>}</main>}
